In [3]:
# libraries
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
from os import listdir
from os.path import join
import cv2
import random


In [5]:
#Path for the input folder
path='D:/Kaggle/flowers/'
#list out the directories inside the main input folder
folders=listdir(path)
print(folders)

['daisy', 'dandelion', 'rose', 'sunflower', 'tulip']


In [8]:
#import the images from the folder and resize them to a 128*128 size
#Also generate the corresponding labels
image_names, train_labels, train_images=[],[],[]
size=64,64
for folder in folders:
    for file in listdir(join(path,folder)):
        if file.endswith("jpg"):
            image_names.append(join(path,folder,file))
            train_labels.append(folder)
            img=cv2.imread(join(path, folder,file))
            im=cv2.resize(img,size)
            train_images.append(im)
        else:
            continue


In [9]:
#Transform the image array to a numpy type
train=np.array(train_images)
train.shape


(4323, 64, 64, 3)

In [10]:
print(train)

[[[[139 141 141]
   [150 149 149]
   [153 152 152]
   ...
   [167 162 163]
   [152 154 154]
   [153 153 153]]

  [[131 136 137]
   [144 145 146]
   [173 167 167]
   ...
   [163 158 159]
   [153 155 155]
   [149 149 149]]

  [[118 125 126]
   [137 140 138]
   [154 154 154]
   ...
   [156 156 156]
   [154 157 157]
   [142 143 144]]

  ...

  [[ 23  44  41]
   [ 25  46  43]
   [ 36  51  49]
   ...
   [122 124 128]
   [118 121 125]
   [117 123 126]]

  [[ 25  46  43]
   [ 25  46  43]
   [ 37  55  54]
   ...
   [126 127 131]
   [124 125 129]
   [122 123 127]]

  [[ 26  47  44]
   [ 27  48  45]
   [ 34  55  53]
   ...
   [132 133 137]
   [128 129 133]
   [125 126 130]]]


 [[[228 221 218]
   [220 213 210]
   [226 219 215]
   ...
   [ 19  24  15]
   [ 17  18  12]
   [ 15   9  11]]

  [[242 233 231]
   [228 223 222]
   [226 218 222]
   ...
   [ 31  34  26]
   [ 19  16  18]
   [ 10   4   7]]

  [[234 230 228]
   [244 238 233]
   [241 235 230]
   ...
   [ 35  30  31]
   [ 21  19  12]
   [ 12   7

In [11]:
#Reduce the RGB values between 0 and 1
train = train.astype('float32')/255.0

In [12]:
import pandas as pd
#extract the lables
label_dummies=pd.get_dummies(train_labels)
labels=label_dummies.values.argmax(1)


In [13]:
print(label_dummies)

      daisy  dandelion  rose  sunflower  tulip
0         1          0     0          0      0
1         1          0     0          0      0
2         1          0     0          0      0
3         1          0     0          0      0
4         1          0     0          0      0
5         1          0     0          0      0
6         1          0     0          0      0
7         1          0     0          0      0
8         1          0     0          0      0
9         1          0     0          0      0
10        1          0     0          0      0
11        1          0     0          0      0
12        1          0     0          0      0
13        1          0     0          0      0
14        1          0     0          0      0
15        1          0     0          0      0
16        1          0     0          0      0
17        1          0     0          0      0
18        1          0     0          0      0
19        1          0     0          0      0
20        1  

In [14]:
print(labels)

[0 0 0 ... 4 4 4]


In [15]:
pd.unique(train_labels)
print(train_labels)

['daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 'daisy', 

In [16]:
pd.unique(train_labels)

array(['daisy', 'dandelion', 'rose', 'sunflower', 'tulip'], dtype=object)

In [17]:
pd.unique(labels)

array([0, 1, 2, 3, 4], dtype=int64)

In [19]:
#shuffle the labels and images randomly for better result
union_list=list(zip(train,labels))
random.shuffle(union_list)
train,labels=zip(*union_list)
#convert the shuffled list to numpy array type
train=np.array(train)
labels=np.array(labels)

In [20]:
#develop a sequential model using tensorflow keras
model=keras.Sequential([
    keras.layers.Flatten(input_shape=(64,64,3)),
    keras.layers.Dense(128, activation=tf.nn.tanh),
    keras.layers.Dense(5,activation=tf.nn.softmax)
])

In [21]:
#compute the model parameters
model.compile(optimizer=tf.train.AdamOptimizer(),
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [23]:
#train the model with 5 epochs
model.fit(train,labels, epochs=10)

Epoch 1/10
4323/4323 [==============================] - 2s 494us/step - loss: 3.8364 - acc: 0.3724
Epoch 2/10
4323/4323 [==============================] - 2s 500us/step - loss: 3.8208 - acc: 0.4009
Epoch 3/10
4323/4323 [==============================] - 2s 515us/step - loss: 3.8095 - acc: 0.3743
Epoch 4/10
4323/4323 [==============================] - 2s 505us/step - loss: 3.4714 - acc: 0.3863
Epoch 5/10
4323/4323 [==============================] - 2s 514us/step - loss: 1.4146 - acc: 0.3706
Epoch 6/10
4323/4323 [==============================] - 2s 510us/step - loss: 1.3700 - acc: 0.3995
Epoch 7/10
4323/4323 [==============================] - 2s 523us/step - loss: 1.3211 - acc: 0.4254
Epoch 8/10
4323/4323 [==============================] - 2s 512us/step - loss: 1.3412 - acc: 0.4180
Epoch 9/10
4323/4323 [==============================] - 2s 517us/step - loss: 1.3375 - acc: 0.4182
Epoch 10/10
4323/4323 [==============================] - 2s 516us/step - loss: 1.3171 - acc: 0.4277
